name: Zara Robotu

on:
  workflow_dispatch:

jobs:
  analiz_yap:
    runs-on: ubuntu-latest
    
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: |
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Robotu Çalıştır
        run: python main.py

      - name: Sonucu Paketle
        uses: actions/upload-artifact@v4
        if: always()  # Hata olsa bile resimleri yükle demek
        with:
          name: kanit-dosyalari
          path: |
            sonuc.json
            *.png
